### PR TITLE
Add Czech (CS) language.

### PR DESCRIPTION
**Pull request by xurban42**

### CODE REVIEW

**Comment by michaelwittig** [comment]
Hi @xurban42 I just saw an wikipedia that CS is used for Serbia and Montenegro and CZ is used for Czechia. There was a reassignment and CS was used for Czechia in the past.
Do you have any background information on this reassignment?
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Transitional_reservations

**Comment by xurban42** [comment]
Hi! That's true, CZ is shortcut for country Czech Republic. But shortcut for czech language is still 'cs'. Locale code is cs_CZ, where cs is czech language and CZ is Czech Republic.

https://www.w3.org/International/articles/language-tags/

**Comment by xurban42** [comment]
http://www.localeplanet.com/icu/cs-CZ/index.html

**Comment by michaelwittig** [comment]
@xurban42 correct be if I'm wrong but this project uses ISO 3166-1 country codes and you are talking about locales as described here: https://en.wikipedia.org/wiki/Locale_(computer_software) ?

**Comment by xurban42** [comment]
@michaelwittig ISO 3166-1 defines country codes, not language codes. You can have different languages than countries. E.g. more languages in one country, serbian language in montenegro, etc.

Languages are defined in ISO639-2: https://www.loc.gov/standards/iso639-2/php/code_list.php <https://www.loc.gov/standards/iso639-2/php/code_list.php> for example.

But it doesn't matter. If you want, I will change it to ‘cz’. No problem. 

:)

**Comment by michaelwittig** [comment]
@xurban42 yes. This project is about country codes. Eventually this does not satisfy your requirements if you look for language codes. But if you would change it to cz that would be a nice contribution to this project :)

**Comment by xurban42** [comment]
@michaelwittig Oh, come on! What are you talking about? This project is about country codes and country names. And country names are different in different languages. I added to your project new language. Here you write: https://github.com/michaelwittig/node-i18n-iso-countries#supported-languages --> SUPPORTED LANGUAGES. Every place where you can see 'cs', it is about language  - there are english, german, dutch... <=== LANGUAGES. And shortcut of czech language is 'cs' not 'CZ'. In country codes it is CZ, i used CZ. This 'cs' is just used like parameter and this parameter specify language -> not country.

**Comment by xurban42** [comment]
And what about China? Country code is CN and in languages you have "zh". "CZ" and "cs" is exactly the same case like "CN" and "zh".

**Comment by gpbl** [comment]
👋 I'm the contributor for zh.json!

I believe @xurban42 is correct. As I've intended this repo, ISO 3166-1 is for the country codes provided in the json files, not about the language, which I myself believed to follow [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).

**Comment by michaelwittig** [comment]
all right. maybe I'm confused or I just don't understand how this works anymore. So let me merge this. releases as i18n-iso-countries@1.6.0

**Pull request merged**
