### PR TITLE
No need to specify list for entry node file

### PR DESCRIPTION
**Pull request by poppinlp**
No need to specify the languages list for entry node file for easier further maintain and reduce possible mismatch here.

### CODE REVIEW

**Comment by michaelwittig** [comment]
I'm closing this since we haven't received feedback from the author of the code that is changed @Ephys

**Comment by Ephys** [comment]
Oh, hello
I'm sorry I don't think I saw the notification for the mention you did a year ago

The only drawback I would see is if you want the node entry point to be bundable (some people bundle their node code to reduce startup time)
If that's not a desired use case, this change should work fine

**Comment by michaelwittig** [comment]
@Ephys do you think this will work in browser environments? I'm not familiar using npm in frontend projects...

**Comment by Ephys** [comment]
@michaelwittig With this PR, this specific file would not work in browser environments anymore, but that shouldn't be an issue because `entry-node` is only loaded by node, `index` will be used by browsers (through bundlers) and is still compatible

**Comment by michaelwittig** [comment]
Thanks @Ephys for helping out here! Much appreciated!

Thanks @poppinlp for contributing 👍

**Comment by michaelwittig** [comment]
I had to revert this change because of #212

**Pull request merged**
