### PR TITLE
Add Kosovo

### PR DESCRIPTION
**Pull request by karlAlnebratt**

### CODE REVIEW

**Comment by michaelwittig** [comment]
Hi @karlAlnebratt The tests are failing because you added a new country code "XK" which is not yet used by any other language. could you add a translation of XK = Kosovo to all the existing languages? I know that this is not easy, but we should keep the availably country codes in sync for all languages.

**Comment by karlAlnebratt** [comment]
Yes i'll look in to that

**Comment by karlAlnebratt** [comment]
@michaelwittig PR is updated and tests i fixed #7af536a

**Comment by michaelwittig** [comment]
Thanks @karlAlnebratt released as i18n-iso-countries@1.8.0

**Comment by emulienfou** [comment]
Numeric code is missing for Kosovo.
According to this link: https://www.statcan.gc.ca/eng/subjects/standard/sccai/2011/scountry-desc the code could be : **983**

**Comment by michaelwittig** [comment]
@emulienfou thanks, added in c4882d71f5b69bbf2ab7c28157e6967272fab7b1

**Pull request merged**
