### PR TITLE
korean nation name edit

### PR DESCRIPTION
**Pull request by dosanHoon**
some korean nation names are wrong

edit offical nation korean name from www.data.go.kr

thank you

### CODE REVIEW

**Comment by michaelwittig** [comment]
If a native speaker could confirm the changes I'm happy to merge them.

**Comment by 9j** [comment]
@michaelwittig @dosanHoon There is a country name that is not an official national name.
Please refer to the website below for the official names of each country used by the Korean government.

https://www.mofa.go.kr/www/nation/m_3458/list.do

**Comment by april-jiyeon-kim** [comment]
@michaelwittig I would appreciate if you merge this file(I am a native korean :) )

**Comment by michaelwittig** [comment]
@april-jiyeon-kim This PR has merge conflicts and can not be merged. I'n not able to resolve the conflicts because I have no idea what is right/wrong. For someone who is familiar with the latin alphabet it is very hard to see differences.

**Comment by april-jiyeon-kim** [comment]
@michaelwittig I see. It seems like the requester isn't very active. Would it be okay if I open a new pull request for the same issue that can be merged, so you can merge the new one and close this one?

**Comment by michaelwittig** [comment]
@april-jiyeon-kim Yes, sounds great! Thank you

**Comment by april-jiyeon-kim** [comment]
@michaelwittig Thanks, I opened a new pr #361

**Pull request closed without merging**
