### PR TITLE
Fixed names not in conformity with ISO 3166-1

### PR DESCRIPTION
**Pull request by Jannchie**
The current naming of Taiwan is not in conformity with [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1).

### CODE REVIEW

**Comment by dhritzkiv** [comment]
I think this PR should be reverted. "Taiwan, Province of China" is a politically charged term that is meant to symbolically strip sovereignty and recognition away from Taiwan, in favour of the People's Republic of China political view.

In the above link, there's a section which cites the naming dispute for Taiwan. See also [the Wikipedia page for the term](https://en.wikipedia.org/wiki/Taiwan%2C_China) for greater context and detail.

Further, while the 2- and 3-letter codes of this library are always consistent with ISO 3166-1, the 'official' names are not: South Korea, North Korea, Holy See (Vatican City State), United Kingdom, Bolivia, Venezuela, etc. And I think that's okay. For an uncontroversial example, "United Kingdom" is a reasonable return value for "GB", as opposed to "United Kingdom of Great Britain and Northern Ireland" – the ISO 3166-1 term.

It's worth looking at other examples of software, namely operating systems and browsers, to see how they deal with the name associated with "TW". For example: everywhere but People's Republic of China and Hong Kong, macOS and iOS uses "Taiwan" to refer to the Republic of China. Same with Microsoft Windows, Mozilla, BSD, etc. For reference, [here is Mozilla's region names list](https://product-details.mozilla.org/1.0/regions/en-US.json), which is based on the US government's [Geopolitical Entities, Names, and Codes (GENC)](https://evs.nci.nih.gov/ftp1/GENC/NCIt-GENC_Terminology.txt)

Lastly, the author of this PR has made similar changes, [including changing Taiwan's flag](https://github.com/Jannchie/flagpack/commit/84ab07f11052364e1dc5e6e20e27584f684cfda6?short_path=c0fe37d) to the national flag of the People's Republic of China. While that change was in his own fork of the repo, I think it demonstrates their motivation of this PR.

**Comment by michaelwittig** [comment]
I added the alternative name after merging this https://github.com/michaelwittig/node-i18n-iso-countries/commit/f1dee5ebe32578758a64a8c385b5fb7541788b78

Still, I don‘t fully agree with your argument that the US view of the world is by definition/force/money the correct one. It‘s more complicated. We have similar discussions around Palestine in #229. both country names will be sooner or later receive a new PR and changed back. I‘m not the authority to decide which countries exist. I‘m getting very tired maintaining this project which I’m not using anymore at all...

**Comment by dhritzkiv** [comment]
Certainly, it's a thankless job especially when it comes to these debates of what a country is, and who calls it what. So: thank you for this project! :)

I can appreciate the problem with defaulting to the US view of the world. My suggestion to base the names on other software was only to align most users' expectations (based on their usage of other software) and to let you wash your hands of these sorts of debates.

**Comment by Jannchie** [comment]
Everyone has a political stance, and the group he is dealing with tends to be the same. But this PR was not meant to express my political views. 

I think this change works for everyone, because that's how it's named on the official ISO website, which you can find on the following website. 
https://www.iso.org/obp/ui/#search. 

This is debatable, of course, but standards should be respected.

**Comment by Jannchie** [comment]
Hi, @samdrivertlol 

Thank you for your passionate response. I acknowledge that the situation in each country and region can be quite complex. I also understand that not everyone agrees with referring to it as Taiwan Province. 

But as a library claiming adherence to ISO standards, it is most impartial to use terminology that aligns with those standards. Deviating from ISO standards to include biases would indeed reflect political inclinations. If you have concerns, it might be more appropriate to address them with those who establish the ISO standards.

**Pull request merged**
