### PR TITLE
Add rollup & support ES modules

### LINKED ISSUE #186: Does not work well with Angular 10
Somehow, your project does not load properly with Angular 10. I used your project forever and starting Angular 10, I get the following error:

```
ERROR in ./src/app/controls/input-address-country/input-address-country.component.ts 35:16-24
"export 'getNames' was not found in 'i18n-iso-countries'
ERROR in ./src/polyfills.ts 62:0-14
"export 'registerLocale' was not found in 'i18n-iso-countries'
```

I load the code like this:

```
import * as countries from 'i18n-iso-countries';

/// ...
countries.registerLocale(require('i18n-iso-countries/langs/en.json'));
countries.getNames('en');
```

It used to work great. Now I try to use your method by using "require" and it doesn't work either.

image

See this:
https://stackoverflow.com/questions/52600104/how-to-use-i18n-iso-countries-in-angular-6

Do you have any recommendations?

### PR DESCRIPTION
**Pull request by hansottowirtz**
This is a WIP. Closes #186.

It adds Rollup and converts the source files to ES modules. When using ES modules in Node, it is not possible to import JSON files. Rollup therefore compiles the `.json` files to `.mjs` and `.js` files. `codes.json` is bundled in every distributed file, and `entry-node.mjs` bundles all languages into one file.

It makes it possible to do the following (from Node 13+, Webpack 5):

```js
import en from "i18n-iso-countries/langs/en";
import countries from "i18n-iso-countries";
countries.registerLocale(countries);
```

or

```js
import entryNode from "i18n-iso-countries/bundled";
```

I'm using it on our Angular 10 website and it works (as Angular CLI uses Webpack 4, I still need to import `i18n-iso-countries/dist/langs/en`).

Anyone can install this branch with NPM by running the command below. I also added a prepare script, which builds the code if the package is being installed from Github.
```bash
npm i hansottowirtz/node-i18n-iso-countries#add-rollup-support-esm
```

More testing is needed before merging this PR, with multiple node versions and with Webpack 5.

### CODE REVIEW

**Comment by KingDarBoja** [comment]
Couldn't find your package on npm, can you share a link? Also, there is a npm package which is a Angualr wrapper for this library: https://www.npmjs.com/package/@ngx-countries/countries

**Comment by hansottowirtz** [comment]
@KingDarBoja I didn't publish a package, but you can use
```
"i18n-iso-countries": "github:hansottowirtz/node-i18n-iso-countries#add-rollup-support-esm"
```
in `package.json`.

**Comment by KingDarBoja** [comment]
Hey @hansottowirtz, can you update the PR with latest changes from master?

**Comment by hansottowirtz** [comment]
@KingDarBoja done 🙂
I also added typings for the `dist/langs/*.mjs` files. These typings aren't resolved yet when using the `exports` field due to https://github.com/microsoft/TypeScript/issues/33079.

**Comment by hansottowirtz** [comment]
It seems like
```js
require('i18n-iso-countries/langs/nl')
```
only started working somewhere after Node `14.5` (`14.15` confirmed working). I added the legacy `"./dist/": "./dist/"` syntax to the `exports` field in order to make it work in older versions of Node as well (legacy because now a `*` is required). They can use
```js
require('i18n-iso-countries/dist/langs/nl.json')
```

**Comment by manzonif** [comment]
installation fails on Windows:
`npm ERR! > i18n-iso-countries@6.2.2 build C:\Users\UserX\AppData\Local\npm-cache\_cacache\tmp\git-clone-71f5291a

npm ERR! > make build

npm ERR! /usr/bin/bash: make: command not found`

And doesn't work with yarn.

**Comment by bschnabel** [comment]
any plans to merge this into master at some point?

**Comment by michaelwittig** [comment]
@bschnabel I don't think that the work here is done. More like a WIP. Correct me if I'm wrong @hansottowirtz ?

**Pull request closed without merging**
