### PR TITLE
Fix Ukrainian spelling

### PR DESCRIPTION
**Pull request by cah4a**
Spot some mistakes.
Harmonize it with [Ukrainian law](https://zakon.rada.gov.ua/rada/show/v0032832-20).

### CODE REVIEW

**Comment by michaelwittig** [comment]
Thanks @cah4a

**Comment by cah4a** [comment]
My pleasure!

**Comment by cah4a** [comment]
Hey @michaelwittig,

I would love to see the fixes in a published version. So I wonder, is there any schedule or plan to publish it?

**Comment by cah4a** [comment]
Thanks!

**Pull request merged**
