### PR TITLE
Add Welsh

### PR DESCRIPTION
**Pull request by cwqt**
...yes, adds Welsh.

### CODE REVIEW

**Comment by michaelwittig** [comment]
Thank you very much! Could you remove the `package-lock.json` file from the PR?

**Comment by cwqt** [comment]
Done :)

**Comment by michaelwittig** [comment]
I guess I wasn't clear. I wanted to see no changes to package-lock.json in your PR. The simple solution could be to copy the file from master and commit it to your branch.

**Comment by cwqt** [comment]
Right - that'll do it

**Comment by michaelwittig** [comment]
Thanks! Released as 6.8.0

**Pull request merged**
