### PR TITLE
Add Traditional Chinese support

### PR DESCRIPTION
**Pull request by fshiori**
Add Traditional Chinese support

### CODE REVIEW

**Comment by michaelwittig** [comment]
Hi @fshiori Thanks for your contribution. So far, the language codes in this library are [ISO 639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes). 

`zh-tw` is not in this list and might be related to #47 

Can we might use a  ISO 639-3 language code listed here: https://en.wikipedia.org/wiki/ISO_639_macrolanguage#zho ? I'm not an expert on languages at all and need help here.

**Comment by fshiori** [comment]
Hello @michaelwittig 
I suggest use BCP 47 to replace ISO 639-1/639-3, too. Like #47 

Because [Mandarin Chinese](https://en.wikipedia.org/wiki/Mandarin_Chinese)(ISO 639-1: zh/ ISO 639-3:cmn/BCP47: zh-Hans) and [Taiwanese Mandarin](https://en.wikipedia.org/wiki/Taiwanese_Mandarin)(BCP47: zh-Hant)have different written word.

**Comment by michaelwittig** [comment]
I believe #47 is about entering a  BCP47 code, and only use the first part before the `-`. But your case is different because `zh` and `zh-tw` are two different things.

**Comment by michaelwittig** [comment]
#94 seems to solve the same use case

**Comment by michaelwittig** [comment]
I found this:
"How does one make distinctions between traditional and simplified Chinese characters and using the ISO 639 language codes?
The differences between traditional and simplified Chinese characters cannot be represented using the ISO 639 codes because these are distinctions in script. The character sets can be coded using ISO 15924 (Code for the Representation of Names of Scripts) script codes as subtags appended to the primary subtag for Chinese."
http://www.loc.gov/standards/iso639-2/faq.html#23

**Comment by fshiori** [comment]
Yes, #94 is solve the same use case. 
And the link describe my question, too.

We can't only use ISO 639 to distinguish between simplified Chinese and traditional Chinese.
Before BCP47, we usually use **zh-tw** for traditional Chinese, use **zh-cn** for simplified Chinese.
https://en.wikipedia.org/wiki/Language_localisation

In BCP47, it add script subtags use ISO 15924 code, so we can use use **zh-Hant** for traditional Chinese, use **zh-Hans** for simplified Chinese, and simple use **zh** for Chinese.

**Comment by michaelwittig** [comment]
I believe that switching from ISO 639-1 codes to BCP47 is more complicated.

`zh`, `az` and `ar` are not a valid "languages" according to https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry They are macrolanguages.

`zh` should likely be changed `zh-Hans`
`ar` I have no idea
`az` I have no idea
...
the list continues

**Comment by fshiori** [comment]
need more work.

**Comment by williamli** [comment]
I think you can extend the current language code to use IETF language tags https://en.wikipedia.org/wiki/IETF_language_tag

en_us = US English
en_gb = UK English

zh_hk = Hong Kong Traditional Chinese
zh_tw = Taiwan Traditional Chinese
zh_cn = Mainland Simplified Chinese

**Comment by nathanaelmartin** [comment]
We need to distinguish : 
zh-Hans :  Simplified Chinese
zh-Hant :  traditional Chinese

**Pull request closed without merging**
